version: "3.9"
services:
  api:
    image: funbuns/kibbl-api:latest
    ports:
      - "8000:5000"
    volumes:
      - .:/app/notes
  frontend:
    image: funbuns/kibbl-frontend:latest
    ports:
      - "8001:5173"
    volumes:
      - .:/app/notes